name: ARC validation pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run arc-export
        run : |
          docker pull ghcr.io/nfdi4plants/arc-export:main  
          docker run -v $(pwd):/arc ghcr.io/nfdi4plants/arc-export:main /arc-export -p arc
          docker run -v $(pwd):/arc ghcr.io/nfdi4plants/arc-export:main /arc-export -p arc -f rocrate-metadata
          docker run -v $(pwd):/arc ghcr.io/nfdi4plants/arc-export:main /arc-export -p arc -f summary-markdown
      - name: Read Results
        uses: actions/upload-artifact@v4
        with:
          name: arc_metadata
          path: | 
            arc-isa.json
            arc-summary.md
            arc-ro-crate-metadata.json
  validate:
    needs: export
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run arc-validate
        run : |
          docker pull ghcr.io/nfdi4plants/arc-validate:main  
          docker run -v $(pwd):/arc ghcr.io/nfdi4plants/arc-validate:main  arc-validate --verbose validate -o ./
      - name: Read Results
        uses: actions/upload-artifact@v4
        with:
          name: validation_results
          path: | 
            .arc-validate-results/arc_specification@2.0.0-draft
      - name: evaluate results
        run: | 
          if grep -q failure .arc-validate-results/arc_specification@2.0.0-draft/validation_report.xml; then
            echo validation failed
            exit 1
          fi


      